<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mbp.xxx.pmp</groupId>
        <artifactId>mbp-pmp-service</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>pmp-module-work</artifactId>

    <properties>
        <!--#####################华丽的分割线_start#####################-->
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!-- Maven 相关 -->
        <maven.clean.plugin.version>3.0.0</maven.clean.plugin.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.plugin.version>3.8.0</maven.compiler.plugin.version>
        <maven.install.plugin.version>2.5.2</maven.install.plugin.version>
        <maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>
        <maven.resources.plugin.version>3.0.2</maven.resources.plugin.version>
        <maven.source.plugin.version>3.2.1</maven.source.plugin.version>
        <maven.surefire.plugin.version>2.20.1</maven.surefire.plugin.version>
        <maven.jar.plugin.version>3.0.2</maven.jar.plugin.version>
        <maven.javadoc.plugin.version>2.9.1</maven.javadoc.plugin.version>
        <maven.gpg.plugin.version>3.0.1</maven.gpg.plugin.version>
        <maven.checkstyle.plugin.version>3.0.0</maven.checkstyle.plugin.version>
        <flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
        <maven.encoding>UTF-8</maven.encoding>
        <maven.charset>UTF-8</maven.charset>
        <maven.docencoding>UTF-8</maven.docencoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--#####################华丽的分割线_end#######################-->
    </properties>

    <dependencies>
        <!-- 通用core -->
        <dependency>
            <groupId>com.kakarote</groupId>
            <artifactId>wk_common_web</artifactId>
            <version>1.0.6</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/resources/lib/wk_common_web-1.0.6.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>com.kakarote.ids</groupId>
            <artifactId>provider</artifactId>
            <version>1.0.1</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/resources/lib/provider-1.0.1.jar</systemPath>
        </dependency>

        <!-- 文件上传 -->
        <dependency>
            <groupId>com.kakarote</groupId>
            <artifactId>wk_common_file</artifactId>
            <version>1.0.5</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/resources/lib/wk_common_file-1.0.6.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>com.mbp.xxx.pmp</groupId>
            <artifactId>pmp-spring-boot-starter-mybatis</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- spring-boot_start -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!--<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>-->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <!-- spring-boot_end -->

        <!--参数验证-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-autoconfigure</artifactId>
        </dependency>

        <!--测试相关_start-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
        <!--测试相关_end-->

        <!-- swagger -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-quartz</artifactId>
        </dependency>

        <!-- redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-starter-redis-lettuce</artifactId>
        </dependency>

        <!-- elasticsearch 版本为7.15.2-->
        <!--<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
        </dependency>-->

        <!-- lombok插件 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
