<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>pmp-common</artifactId>
        <groupId>com.mbp.xxx.pmp</groupId>
        <version>${revision}</version>
    </parent>

    <packaging>jar</packaging>
    <artifactId>res</artifactId>

    <properties>
        <!--#####################华丽的分割线_start#####################-->
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!-- Maven 相关 -->
        <maven.clean.plugin.version>3.0.0</maven.clean.plugin.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.plugin.version>3.8.0</maven.compiler.plugin.version>
        <maven.install.plugin.version>2.5.2</maven.install.plugin.version>
        <maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>
        <maven.resources.plugin.version>3.0.2</maven.resources.plugin.version>
        <maven.source.plugin.version>3.2.1</maven.source.plugin.version>
        <maven.surefire.plugin.version>2.20.1</maven.surefire.plugin.version>
        <maven.jar.plugin.version>3.0.2</maven.jar.plugin.version>
        <maven.javadoc.plugin.version>2.9.1</maven.javadoc.plugin.version>
        <maven.gpg.plugin.version>3.0.1</maven.gpg.plugin.version>
        <maven.checkstyle.plugin.version>3.0.0</maven.checkstyle.plugin.version>
        <flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
        <maven.encoding>UTF-8</maven.encoding>
        <maven.charset>UTF-8</maven.charset>
        <maven.docencoding>UTF-8</maven.docencoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--#####################华丽的分割线_end#######################-->
    </properties>

    <dependencies>
        <!--模块-framework-common相关_start-->
        <dependency>
            <groupId>com.mbp.xxx.pmp</groupId>
            <artifactId>util</artifactId>
        </dependency>
        <!--模块-framework-common相关_end-->

        <!-- Spring 核心 -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <!-- 设置为 provided,主要是 PageParam 使用到 -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <!-- 设置为 provided,只有工具类需要使用到 -->
            <scope>provided</scope>
        </dependency>

        <!-- 用于生成自定义的 Spring @ConfigurationProperties 配置类的说明文件 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <!-- 设置为 provided,只有工具类需要使用到 -->
            <scope>provided</scope>
        </dependency>

        <!-- 监控相关 -->
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>

        <!-- 工具类相关 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>

        <!-- use mapstruct-jdk8 for Java 8 or higher -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-jdk8</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <!-- 设置为 provided,只有工具类需要使用到 -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <!-- 设置为 provided,只有工具类需要使用到 -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <!-- 设置为 provided,只有工具类需要使用到 -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <!-- 设置为 provided,只有工具类需要使用到 -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <!-- 设置为 provided,主要是 PageParam 使用到 -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>transmittable-thread-local</artifactId>
        </dependency>

        <!-- 默认引入的原因,方便 xxx-module-api 包使用 -->
        <!-- VO 数据翻译 -->
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>easy-trans-anno</artifactId>
        </dependency>
    </dependencies>
</project>